Theodosious_test: ./test.o ../src/module/gpio.o ../src/module/mem.o
	gcc -o ./Theodosious_test ./test.o ../src/module/gpio.o ../src/module/mem.o
main.o:	./test.c
	gcc -c ./test.c
gpio.o: ../src/module/gpio.c
	gcc -c ../src/module/gpio.c
mem.o: ../src/module/me.c
	gcc -c ../src/module/mem.c	
